name: Refresh CDN

on:
  push:
    branches:
      - main

jobs:
  refresh-cdn:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 等待源站部署
        run: sleep 1m  # 这里用了个笨办法，等待 1 分钟后进行刷新

      - name: 刷新 CDN
        run: python .github/RefreshCDN.py
        env:
          DOGECLOUD_ACCESS_KEY: ${{ secrets.DOGECLOUD_ACCESS_KEY }}
          DOGECLOUD_SECRET_KEY: ${{ secrets.DOGECLOUD_SECRET_KEY }}
          CDN_URL_LIST: ${{ secrets.CDN_URL_LIST }}